### ISSUE TITLE
Doesn't play nice with Appindicator and KstatusNotifierItem Support

### ISSUE THREAD

**Issue by techtino** [Noobsai/fullscreen-avoider#9] opened 2022-08-22 17:51 UTC
When using with that extension, it works fine to move the bar, but upon the bar moving back, the tray icons from that extension don't come back with it, disable and re-enabling the appindicator extension fixes it.

**Comment by Noobsai** [comment] 2022-08-22 19:24
Hello. This is problem of all tray icon extensions, I cannot fix the root cause from my side, I can only rebuild tray icons. Please test the [extension.js](https://github.com/Noobsai/fullscreen-avoider/blob/fix-appindicatorsupport/src/extension.js) from new branch. 
This fix just disable and enable the Appindicator extension after moving the panel. But it doesn't work properly on my machine. I had empty spaces after each re-enabling until restarting the shell. If ok I will add this fix to the main. 
So if you can I recommend to use [Tray Icons: Reloaded](https://extensions.gnome.org/extension/2890/tray-icons-reloaded/). I have some fix for this extension what works properly

**Comment by techtino** [comment] 2022-08-22 21:21
Hi! Thank you for the response. I suspected that would be the case, I'll give that extension a go.

**Closed** 2022-09-02 10:32 UTC
